// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p4/config/p4info.proto

/*
Package p4_config is a generated protocol buffer package.

It is generated from these files:
	p4/config/p4info.proto

It has these top-level messages:
	P4Info
	Documentation
	PkgInfo
	P4Ids
	Preamble
	Extern
	ExternInstance
	MatchField
	Table
	ActionRef
	Action
	ActionProfile
	CounterSpec
	Counter
	DirectCounter
	MeterSpec
	Meter
	DirectMeter
	ControllerPacketMetadata
	ValueSet
	Register
	Digest
*/
package p4_config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ids are allocated in such a way that it is possible based on an id to
// deduce the resource type (e.g. table, action, counter, ...). The
// most-significant byte of the 32-bit id encodes the resource type. The
// purpose of this enum is to define which value is used as the
// most-significant byte for each resource type. The P4 compiler must use
// these values when allocating ids for P4 objects. Other users of P4Info can
// refer to this enum to identify a resource type based on its id.
type P4Ids_Prefix int32

const (
	P4Ids_UNSPECIFIED P4Ids_Prefix = 0
	// P4 language built-ins
	P4Ids_ACTION            P4Ids_Prefix = 1
	P4Ids_TABLE             P4Ids_Prefix = 2
	P4Ids_VALUE_SET         P4Ids_Prefix = 3
	P4Ids_CONTROLLER_HEADER P4Ids_Prefix = 4
	// PSA externs
	P4Ids_PSA_EXTERNS_START P4Ids_Prefix = 16
	P4Ids_ACTION_PROFILE    P4Ids_Prefix = 17
	P4Ids_COUNTER           P4Ids_Prefix = 18
	P4Ids_DIRECT_COUNTER    P4Ids_Prefix = 19
	P4Ids_METER             P4Ids_Prefix = 20
	P4Ids_DIRECT_METER      P4Ids_Prefix = 21
	P4Ids_REGISTER          P4Ids_Prefix = 22
	P4Ids_DIGEST            P4Ids_Prefix = 23
	// externs for other architectures (vendor extensions)
	P4Ids_OTHER_EXTERNS_START P4Ids_Prefix = 128
	// max value for an unsigned 8-bit byte
	P4Ids_MAX P4Ids_Prefix = 255
)

var P4Ids_Prefix_name = map[int32]string{
	0:   "UNSPECIFIED",
	1:   "ACTION",
	2:   "TABLE",
	3:   "VALUE_SET",
	4:   "CONTROLLER_HEADER",
	16:  "PSA_EXTERNS_START",
	17:  "ACTION_PROFILE",
	18:  "COUNTER",
	19:  "DIRECT_COUNTER",
	20:  "METER",
	21:  "DIRECT_METER",
	22:  "REGISTER",
	23:  "DIGEST",
	128: "OTHER_EXTERNS_START",
	255: "MAX",
}
var P4Ids_Prefix_value = map[string]int32{
	"UNSPECIFIED":         0,
	"ACTION":              1,
	"TABLE":               2,
	"VALUE_SET":           3,
	"CONTROLLER_HEADER":   4,
	"PSA_EXTERNS_START":   16,
	"ACTION_PROFILE":      17,
	"COUNTER":             18,
	"DIRECT_COUNTER":      19,
	"METER":               20,
	"DIRECT_METER":        21,
	"REGISTER":            22,
	"DIGEST":              23,
	"OTHER_EXTERNS_START": 128,
	"MAX": 255,
}

func (x P4Ids_Prefix) String() string {
	return proto.EnumName(P4Ids_Prefix_name, int32(x))
}
func (P4Ids_Prefix) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type MatchField_MatchType int32

const (
	MatchField_UNSPECIFIED MatchField_MatchType = 0
	MatchField_VALID       MatchField_MatchType = 1
	MatchField_EXACT       MatchField_MatchType = 2
	MatchField_LPM         MatchField_MatchType = 3
	MatchField_TERNARY     MatchField_MatchType = 4
	MatchField_RANGE       MatchField_MatchType = 5
)

var MatchField_MatchType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "VALID",
	2: "EXACT",
	3: "LPM",
	4: "TERNARY",
	5: "RANGE",
}
var MatchField_MatchType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"VALID":       1,
	"EXACT":       2,
	"LPM":         3,
	"TERNARY":     4,
	"RANGE":       5,
}

func (x MatchField_MatchType) String() string {
	return proto.EnumName(MatchField_MatchType_name, int32(x))
}
func (MatchField_MatchType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

// Corresponds to 'type' attribute for counter in P4 spec.
type CounterSpec_Unit int32

const (
	CounterSpec_UNSPECIFIED CounterSpec_Unit = 0
	CounterSpec_BYTES       CounterSpec_Unit = 1
	CounterSpec_PACKETS     CounterSpec_Unit = 2
	CounterSpec_BOTH        CounterSpec_Unit = 3
)

var CounterSpec_Unit_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "BYTES",
	2: "PACKETS",
	3: "BOTH",
}
var CounterSpec_Unit_value = map[string]int32{
	"UNSPECIFIED": 0,
	"BYTES":       1,
	"PACKETS":     2,
	"BOTH":        3,
}

func (x CounterSpec_Unit) String() string {
	return proto.EnumName(CounterSpec_Unit_name, int32(x))
}
func (CounterSpec_Unit) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12, 0} }

// Corresponds to 'type' attribute for meter in P4 spec.
type MeterSpec_Unit int32

const (
	MeterSpec_UNSPECIFIED MeterSpec_Unit = 0
	MeterSpec_BYTES       MeterSpec_Unit = 1
	MeterSpec_PACKETS     MeterSpec_Unit = 2
)

var MeterSpec_Unit_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "BYTES",
	2: "PACKETS",
}
var MeterSpec_Unit_value = map[string]int32{
	"UNSPECIFIED": 0,
	"BYTES":       1,
	"PACKETS":     2,
}

func (x MeterSpec_Unit) String() string {
	return proto.EnumName(MeterSpec_Unit_name, int32(x))
}
func (MeterSpec_Unit) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 0} }

// Not part of the P4 spec yet but will be in the future.
type MeterSpec_Type int32

const (
	MeterSpec_COLOR_UNAWARE MeterSpec_Type = 0
	MeterSpec_COLOR_AWARE   MeterSpec_Type = 1
)

var MeterSpec_Type_name = map[int32]string{
	0: "COLOR_UNAWARE",
	1: "COLOR_AWARE",
}
var MeterSpec_Type_value = map[string]int32{
	"COLOR_UNAWARE": 0,
	"COLOR_AWARE":   1,
}

func (x MeterSpec_Type) String() string {
	return proto.EnumName(MeterSpec_Type_name, int32(x))
}
func (MeterSpec_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 1} }

type P4Info struct {
	PkgInfo                  *PkgInfo                    `protobuf:"bytes,1,opt,name=pkg_info,json=pkgInfo" json:"pkg_info,omitempty"`
	Tables                   []*Table                    `protobuf:"bytes,2,rep,name=tables" json:"tables,omitempty"`
	Actions                  []*Action                   `protobuf:"bytes,3,rep,name=actions" json:"actions,omitempty"`
	ActionProfiles           []*ActionProfile            `protobuf:"bytes,4,rep,name=action_profiles,json=actionProfiles" json:"action_profiles,omitempty"`
	Counters                 []*Counter                  `protobuf:"bytes,5,rep,name=counters" json:"counters,omitempty"`
	DirectCounters           []*DirectCounter            `protobuf:"bytes,6,rep,name=direct_counters,json=directCounters" json:"direct_counters,omitempty"`
	Meters                   []*Meter                    `protobuf:"bytes,7,rep,name=meters" json:"meters,omitempty"`
	DirectMeters             []*DirectMeter              `protobuf:"bytes,8,rep,name=direct_meters,json=directMeters" json:"direct_meters,omitempty"`
	ControllerPacketMetadata []*ControllerPacketMetadata `protobuf:"bytes,9,rep,name=controller_packet_metadata,json=controllerPacketMetadata" json:"controller_packet_metadata,omitempty"`
	ValueSets                []*ValueSet                 `protobuf:"bytes,10,rep,name=value_sets,json=valueSets" json:"value_sets,omitempty"`
	Registers                []*Register                 `protobuf:"bytes,11,rep,name=registers" json:"registers,omitempty"`
	Digests                  []*Digest                   `protobuf:"bytes,12,rep,name=digests" json:"digests,omitempty"`
	Externs                  []*Extern                   `protobuf:"bytes,100,rep,name=externs" json:"externs,omitempty"`
}

func (m *P4Info) Reset()                    { *m = P4Info{} }
func (m *P4Info) String() string            { return proto.CompactTextString(m) }
func (*P4Info) ProtoMessage()               {}
func (*P4Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *P4Info) GetPkgInfo() *PkgInfo {
	if m != nil {
		return m.PkgInfo
	}
	return nil
}

func (m *P4Info) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *P4Info) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *P4Info) GetActionProfiles() []*ActionProfile {
	if m != nil {
		return m.ActionProfiles
	}
	return nil
}

func (m *P4Info) GetCounters() []*Counter {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *P4Info) GetDirectCounters() []*DirectCounter {
	if m != nil {
		return m.DirectCounters
	}
	return nil
}

func (m *P4Info) GetMeters() []*Meter {
	if m != nil {
		return m.Meters
	}
	return nil
}

func (m *P4Info) GetDirectMeters() []*DirectMeter {
	if m != nil {
		return m.DirectMeters
	}
	return nil
}

func (m *P4Info) GetControllerPacketMetadata() []*ControllerPacketMetadata {
	if m != nil {
		return m.ControllerPacketMetadata
	}
	return nil
}

func (m *P4Info) GetValueSets() []*ValueSet {
	if m != nil {
		return m.ValueSets
	}
	return nil
}

func (m *P4Info) GetRegisters() []*Register {
	if m != nil {
		return m.Registers
	}
	return nil
}

func (m *P4Info) GetDigests() []*Digest {
	if m != nil {
		return m.Digests
	}
	return nil
}

func (m *P4Info) GetExterns() []*Extern {
	if m != nil {
		return m.Externs
	}
	return nil
}

type Documentation struct {
	// A brief description of something, e.g. one sentence
	Brief string `protobuf:"bytes,1,opt,name=brief" json:"brief,omitempty"`
	// A more verbose description of something. Multiline is accepted. Markup format (if any) is TBD.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Documentation) Reset()                    { *m = Documentation{} }
func (m *Documentation) String() string            { return proto.CompactTextString(m) }
func (*Documentation) ProtoMessage()               {}
func (*Documentation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Documentation) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

func (m *Documentation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// Top-level package documentation describing the forwarding pipeline config
// Can be used to manage multiple P4 packages.
type PkgInfo struct {
	// a definitive name for this configuration, e.g. switch.p4_v1.0
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// configuration version, free-format string
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	// brief and detailed descriptions
	Doc *Documentation `protobuf:"bytes,3,opt,name=doc" json:"doc,omitempty"`
	// Miscellaneous metadata, free-form; a way to extend PkgInfo
	Annotations []string `protobuf:"bytes,4,rep,name=annotations" json:"annotations,omitempty"`
	// the target architecture, e.g. "psa"
	Arch string `protobuf:"bytes,5,opt,name=arch" json:"arch,omitempty"`
	// organization which produced the configuration, e.g. "p4.org"
	Organization string `protobuf:"bytes,6,opt,name=organization" json:"organization,omitempty"`
	// contact info for support,e.g. "tech-support@acme.org"
	Contact string `protobuf:"bytes,7,opt,name=contact" json:"contact,omitempty"`
	// url for more information, e.g. "http://support.p4.org/ref/p4/switch.p4_v1.0"
	Url string `protobuf:"bytes,8,opt,name=url" json:"url,omitempty"`
}

func (m *PkgInfo) Reset()                    { *m = PkgInfo{} }
func (m *PkgInfo) String() string            { return proto.CompactTextString(m) }
func (*PkgInfo) ProtoMessage()               {}
func (*PkgInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PkgInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PkgInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PkgInfo) GetDoc() *Documentation {
	if m != nil {
		return m.Doc
	}
	return nil
}

func (m *PkgInfo) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *PkgInfo) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *PkgInfo) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *PkgInfo) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *PkgInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// wrapping the enum in a message to avoid name collisions in C++, where "enum
// values are siblings of their type, not children of it"
type P4Ids struct {
}

func (m *P4Ids) Reset()                    { *m = P4Ids{} }
func (m *P4Ids) String() string            { return proto.CompactTextString(m) }
func (*P4Ids) ProtoMessage()               {}
func (*P4Ids) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Preamble struct {
	// ids share the same number-space; e.g. table ids cannot overlap with counter
	// ids. Even though this is irrelevant to this proto definition, the ids are
	// allocated in such a way that it is possible based on an id to deduce the
	// resource type (e.g. table, action, counter, ...). This means that code
	// using these ids can detect if the wrong resource type is used
	// somewhere. This also means that ids of different types can be mixed
	// (e.g. direct resource list for a table) without ambiguity. Note that id 0
	// is reserved and means "invalid id".
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// fully qualified name of the P4 object, e.g. c1.c2.ipv4_lpm
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// an alias for the P4 object, probably shorter than its name. The only
	// constraint is for it to be unique with respect to other P4 objects of the
	// same type. By default, the compiler uses the shortest suffix of the name
	// that uniquely identifies the object. For example if the P4 program
	// contains two tables with names s.c1.t and s.c2.t, the default aliases will
	// respectively be c1.t and c2.t. The P4 programmer may also override the
	// default alias for any P4 object (TBD). When resolving a P4 object id, an
	// application should be able to indiscriminately use the name or the alias.
	Alias       string   `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
	Annotations []string `protobuf:"bytes,4,rep,name=annotations" json:"annotations,omitempty"`
	// Documentation of the entity
	Doc *Documentation `protobuf:"bytes,5,opt,name=doc" json:"doc,omitempty"`
}

func (m *Preamble) Reset()                    { *m = Preamble{} }
func (m *Preamble) String() string            { return proto.CompactTextString(m) }
func (*Preamble) ProtoMessage()               {}
func (*Preamble) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Preamble) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Preamble) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Preamble) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Preamble) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Preamble) GetDoc() *Documentation {
	if m != nil {
		return m.Doc
	}
	return nil
}

// used to group all extern instances of the same type in one message
type Extern struct {
	// the extern_type_id is assigned during compilation. It is likely that this
	// id will in fact come from a P4 annotation to the extern declaration and
	// that each vendor will receive a prefix to avoid collisions.
	ExternTypeId   uint32            `protobuf:"varint,1,opt,name=extern_type_id,json=externTypeId" json:"extern_type_id,omitempty"`
	ExternTypeName string            `protobuf:"bytes,2,opt,name=extern_type_name,json=externTypeName" json:"extern_type_name,omitempty"`
	Instances      []*ExternInstance `protobuf:"bytes,3,rep,name=instances" json:"instances,omitempty"`
}

func (m *Extern) Reset()                    { *m = Extern{} }
func (m *Extern) String() string            { return proto.CompactTextString(m) }
func (*Extern) ProtoMessage()               {}
func (*Extern) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Extern) GetExternTypeId() uint32 {
	if m != nil {
		return m.ExternTypeId
	}
	return 0
}

func (m *Extern) GetExternTypeName() string {
	if m != nil {
		return m.ExternTypeName
	}
	return ""
}

func (m *Extern) GetInstances() []*ExternInstance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type ExternInstance struct {
	Preamble *Preamble `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	// specific to the extern type, declared in a separate vendor-specific proto
	// file
	Info *google_protobuf.Any `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *ExternInstance) Reset()                    { *m = ExternInstance{} }
func (m *ExternInstance) String() string            { return proto.CompactTextString(m) }
func (*ExternInstance) ProtoMessage()               {}
func (*ExternInstance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ExternInstance) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *ExternInstance) GetInfo() *google_protobuf.Any {
	if m != nil {
		return m.Info
	}
	return nil
}

// TODO(antonin): define inside the Table message?
type MatchField struct {
	Id          uint32               `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Annotations []string             `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty"`
	Bitwidth    int32                `protobuf:"varint,4,opt,name=bitwidth" json:"bitwidth,omitempty"`
	MatchType   MatchField_MatchType `protobuf:"varint,5,opt,name=match_type,json=matchType,enum=p4.config.MatchField_MatchType" json:"match_type,omitempty"`
	// Documentation of the match field
	Doc *Documentation `protobuf:"bytes,6,opt,name=doc" json:"doc,omitempty"`
}

func (m *MatchField) Reset()                    { *m = MatchField{} }
func (m *MatchField) String() string            { return proto.CompactTextString(m) }
func (*MatchField) ProtoMessage()               {}
func (*MatchField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MatchField) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MatchField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MatchField) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *MatchField) GetBitwidth() int32 {
	if m != nil {
		return m.Bitwidth
	}
	return 0
}

func (m *MatchField) GetMatchType() MatchField_MatchType {
	if m != nil {
		return m.MatchType
	}
	return MatchField_UNSPECIFIED
}

func (m *MatchField) GetDoc() *Documentation {
	if m != nil {
		return m.Doc
	}
	return nil
}

type Table struct {
	Preamble    *Preamble     `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	MatchFields []*MatchField `protobuf:"bytes,2,rep,name=match_fields,json=matchFields" json:"match_fields,omitempty"`
	// even when the table is indirect (see implementation_id) below, this field
	// includes all possible actions for the table; by using ActionRef instead of
	// a repeated field of action ids, each action reference in a P4 table is able
	// to have its own annotations
	ActionRefs []*ActionRef `protobuf:"bytes,3,rep,name=action_refs,json=actionRefs" json:"action_refs,omitempty"`
	// 0 (default value) means that the table does not have a const default action
	ConstDefaultActionId uint32 `protobuf:"varint,4,opt,name=const_default_action_id,json=constDefaultActionId" json:"const_default_action_id,omitempty"`
	// a table may have a const default action, whose action parameter values can
	// be changed at runtime. However, in most cases the parameters of the default
	// action are also bound at compile-time and cannot be changed by the runtime,
	// which is what this boolean flag indicates.
	ConstDefaultActionHasMutableParams bool `protobuf:"varint,5,opt,name=const_default_action_has_mutable_params,json=constDefaultActionHasMutableParams" json:"const_default_action_has_mutable_params,omitempty"`
	// P4 id of the "implementation" for this table (e.g. action profile id); 0
	// (default value) means that the table is a regular (direct) match table. As
	// of today, only action profiles are supported but other table
	// implementations may be added in the future
	ImplementationId uint32 `protobuf:"varint,6,opt,name=implementation_id,json=implementationId" json:"implementation_id,omitempty"`
	// ids of the direct resources (if any) attached to this table; for now this
	// includes only direct counters and direct meters, but other resources may be
	// added in the future
	DirectResourceIds []uint32 `protobuf:"varint,7,rep,packed,name=direct_resource_ids,json=directResourceIds" json:"direct_resource_ids,omitempty"`
	Size              int64    `protobuf:"varint,8,opt,name=size" json:"size,omitempty"`
	WithEntryTimeout  bool     `protobuf:"varint,9,opt,name=with_entry_timeout,json=withEntryTimeout" json:"with_entry_timeout,omitempty"`
	// table with static P4 entries, cannot be modified at runtime
	IsConstTable bool `protobuf:"varint,10,opt,name=is_const_table,json=isConstTable" json:"is_const_table,omitempty"`
}

func (m *Table) Reset()                    { *m = Table{} }
func (m *Table) String() string            { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()               {}
func (*Table) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Table) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *Table) GetMatchFields() []*MatchField {
	if m != nil {
		return m.MatchFields
	}
	return nil
}

func (m *Table) GetActionRefs() []*ActionRef {
	if m != nil {
		return m.ActionRefs
	}
	return nil
}

func (m *Table) GetConstDefaultActionId() uint32 {
	if m != nil {
		return m.ConstDefaultActionId
	}
	return 0
}

func (m *Table) GetConstDefaultActionHasMutableParams() bool {
	if m != nil {
		return m.ConstDefaultActionHasMutableParams
	}
	return false
}

func (m *Table) GetImplementationId() uint32 {
	if m != nil {
		return m.ImplementationId
	}
	return 0
}

func (m *Table) GetDirectResourceIds() []uint32 {
	if m != nil {
		return m.DirectResourceIds
	}
	return nil
}

func (m *Table) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Table) GetWithEntryTimeout() bool {
	if m != nil {
		return m.WithEntryTimeout
	}
	return false
}

func (m *Table) GetIsConstTable() bool {
	if m != nil {
		return m.IsConstTable
	}
	return false
}

// used to list all possible actions in a Table
type ActionRef struct {
	Id          uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Annotations []string `protobuf:"bytes,2,rep,name=annotations" json:"annotations,omitempty"`
}

func (m *ActionRef) Reset()                    { *m = ActionRef{} }
func (m *ActionRef) String() string            { return proto.CompactTextString(m) }
func (*ActionRef) ProtoMessage()               {}
func (*ActionRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ActionRef) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ActionRef) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

type Action struct {
	Preamble *Preamble       `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	Params   []*Action_Param `protobuf:"bytes,2,rep,name=params" json:"params,omitempty"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Action) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *Action) GetParams() []*Action_Param {
	if m != nil {
		return m.Params
	}
	return nil
}

type Action_Param struct {
	Id          uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Annotations []string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty"`
	Bitwidth    int32    `protobuf:"varint,4,opt,name=bitwidth" json:"bitwidth,omitempty"`
	// Documentation of the Param
	Doc *Documentation `protobuf:"bytes,5,opt,name=doc" json:"doc,omitempty"`
}

func (m *Action_Param) Reset()                    { *m = Action_Param{} }
func (m *Action_Param) String() string            { return proto.CompactTextString(m) }
func (*Action_Param) ProtoMessage()               {}
func (*Action_Param) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

func (m *Action_Param) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Action_Param) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action_Param) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Action_Param) GetBitwidth() int32 {
	if m != nil {
		return m.Bitwidth
	}
	return 0
}

func (m *Action_Param) GetDoc() *Documentation {
	if m != nil {
		return m.Doc
	}
	return nil
}

type ActionProfile struct {
	Preamble *Preamble `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	// the ids of the tables sharing this action profile
	TableIds []uint32 `protobuf:"varint,2,rep,packed,name=table_ids,json=tableIds" json:"table_ids,omitempty"`
	// true iff the action profile used dynamic selection
	WithSelector bool  `protobuf:"varint,3,opt,name=with_selector,json=withSelector" json:"with_selector,omitempty"`
	Size         int64 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
}

func (m *ActionProfile) Reset()                    { *m = ActionProfile{} }
func (m *ActionProfile) String() string            { return proto.CompactTextString(m) }
func (*ActionProfile) ProtoMessage()               {}
func (*ActionProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ActionProfile) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *ActionProfile) GetTableIds() []uint32 {
	if m != nil {
		return m.TableIds
	}
	return nil
}

func (m *ActionProfile) GetWithSelector() bool {
	if m != nil {
		return m.WithSelector
	}
	return false
}

func (m *ActionProfile) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type CounterSpec struct {
	Unit CounterSpec_Unit `protobuf:"varint,1,opt,name=unit,enum=p4.config.CounterSpec_Unit" json:"unit,omitempty"`
}

func (m *CounterSpec) Reset()                    { *m = CounterSpec{} }
func (m *CounterSpec) String() string            { return proto.CompactTextString(m) }
func (*CounterSpec) ProtoMessage()               {}
func (*CounterSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CounterSpec) GetUnit() CounterSpec_Unit {
	if m != nil {
		return m.Unit
	}
	return CounterSpec_UNSPECIFIED
}

type Counter struct {
	Preamble *Preamble    `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	Spec     *CounterSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	// number of entries in the counter array
	Size int64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *Counter) Reset()                    { *m = Counter{} }
func (m *Counter) String() string            { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()               {}
func (*Counter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Counter) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *Counter) GetSpec() *CounterSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Counter) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type DirectCounter struct {
	Preamble *Preamble    `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	Spec     *CounterSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	// the id of the table to which the counter is attached
	DirectTableId uint32 `protobuf:"varint,3,opt,name=direct_table_id,json=directTableId" json:"direct_table_id,omitempty"`
}

func (m *DirectCounter) Reset()                    { *m = DirectCounter{} }
func (m *DirectCounter) String() string            { return proto.CompactTextString(m) }
func (*DirectCounter) ProtoMessage()               {}
func (*DirectCounter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DirectCounter) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *DirectCounter) GetSpec() *CounterSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *DirectCounter) GetDirectTableId() uint32 {
	if m != nil {
		return m.DirectTableId
	}
	return 0
}

type MeterSpec struct {
	Unit MeterSpec_Unit `protobuf:"varint,1,opt,name=unit,enum=p4.config.MeterSpec_Unit" json:"unit,omitempty"`
	Type MeterSpec_Type `protobuf:"varint,2,opt,name=type,enum=p4.config.MeterSpec_Type" json:"type,omitempty"`
}

func (m *MeterSpec) Reset()                    { *m = MeterSpec{} }
func (m *MeterSpec) String() string            { return proto.CompactTextString(m) }
func (*MeterSpec) ProtoMessage()               {}
func (*MeterSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *MeterSpec) GetUnit() MeterSpec_Unit {
	if m != nil {
		return m.Unit
	}
	return MeterSpec_UNSPECIFIED
}

func (m *MeterSpec) GetType() MeterSpec_Type {
	if m != nil {
		return m.Type
	}
	return MeterSpec_COLOR_UNAWARE
}

type Meter struct {
	Preamble *Preamble  `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	Spec     *MeterSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	// number of entries in the meter array
	Size int64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *Meter) Reset()                    { *m = Meter{} }
func (m *Meter) String() string            { return proto.CompactTextString(m) }
func (*Meter) ProtoMessage()               {}
func (*Meter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Meter) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *Meter) GetSpec() *MeterSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Meter) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type DirectMeter struct {
	Preamble *Preamble  `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	Spec     *MeterSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	// the id of the table to which the meter is attached
	DirectTableId uint32 `protobuf:"varint,3,opt,name=direct_table_id,json=directTableId" json:"direct_table_id,omitempty"`
}

func (m *DirectMeter) Reset()                    { *m = DirectMeter{} }
func (m *DirectMeter) String() string            { return proto.CompactTextString(m) }
func (*DirectMeter) ProtoMessage()               {}
func (*DirectMeter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DirectMeter) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *DirectMeter) GetSpec() *MeterSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *DirectMeter) GetDirectTableId() uint32 {
	if m != nil {
		return m.DirectTableId
	}
	return 0
}

// Any metadata associated with controller Packet-IO (Packet-In or Packet-Out)
// is modeled as P4 headers carrying special annotations
// @controller_metadata("packet_out") and @controller_metadata("packet_in")
// respectively. There can be at most one header each with these annotations.
// This message captures the info contained within these special headers,
// and used in p4runtime.proto to supply the metadata.
type ControllerPacketMetadata struct {
	// preamble.name and preamble.id will specify header type ("packet_out" or
	// "packet_in" for now).
	Preamble *Preamble `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	// Ordered based on header layout.
	// This is a constraint on the generator of this P4Info.
	Metadata []*ControllerPacketMetadata_Metadata `protobuf:"bytes,2,rep,name=metadata" json:"metadata,omitempty"`
}

func (m *ControllerPacketMetadata) Reset()                    { *m = ControllerPacketMetadata{} }
func (m *ControllerPacketMetadata) String() string            { return proto.CompactTextString(m) }
func (*ControllerPacketMetadata) ProtoMessage()               {}
func (*ControllerPacketMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ControllerPacketMetadata) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *ControllerPacketMetadata) GetMetadata() []*ControllerPacketMetadata_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ControllerPacketMetadata_Metadata struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// This is the name of the header field (not fully-qualified), similar
	// to e.g. Action.Param.name.
	Name        string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Annotations []string `protobuf:"bytes,3,rep,name=annotations" json:"annotations,omitempty"`
	Bitwidth    int32    `protobuf:"varint,4,opt,name=bitwidth" json:"bitwidth,omitempty"`
}

func (m *ControllerPacketMetadata_Metadata) Reset()         { *m = ControllerPacketMetadata_Metadata{} }
func (m *ControllerPacketMetadata_Metadata) String() string { return proto.CompactTextString(m) }
func (*ControllerPacketMetadata_Metadata) ProtoMessage()    {}
func (*ControllerPacketMetadata_Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18, 0}
}

func (m *ControllerPacketMetadata_Metadata) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ControllerPacketMetadata_Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ControllerPacketMetadata_Metadata) GetAnnotations() []string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *ControllerPacketMetadata_Metadata) GetBitwidth() int32 {
	if m != nil {
		return m.Bitwidth
	}
	return 0
}

type ValueSet struct {
	Preamble *Preamble `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	Bitwidth int32     `protobuf:"varint,2,opt,name=bitwidth" json:"bitwidth,omitempty"`
	// The value set size should be extracted from the @size annotation into the
	// field below. The @size annotation will also appear in the preamble.
	Size int32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *ValueSet) Reset()                    { *m = ValueSet{} }
func (m *ValueSet) String() string            { return proto.CompactTextString(m) }
func (*ValueSet) ProtoMessage()               {}
func (*ValueSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ValueSet) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *ValueSet) GetBitwidth() int32 {
	if m != nil {
		return m.Bitwidth
	}
	return 0
}

func (m *ValueSet) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Register struct {
	Preamble *Preamble `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
	// P4DataTypeSpec type_spec = 2;
	Size int32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *Register) Reset()                    { *m = Register{} }
func (m *Register) String() string            { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()               {}
func (*Register) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Register) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func (m *Register) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Digest struct {
	Preamble *Preamble `protobuf:"bytes,1,opt,name=preamble" json:"preamble,omitempty"`
}

func (m *Digest) Reset()                    { *m = Digest{} }
func (m *Digest) String() string            { return proto.CompactTextString(m) }
func (*Digest) ProtoMessage()               {}
func (*Digest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *Digest) GetPreamble() *Preamble {
	if m != nil {
		return m.Preamble
	}
	return nil
}

func init() {
	proto.RegisterType((*P4Info)(nil), "p4.config.P4Info")
	proto.RegisterType((*Documentation)(nil), "p4.config.Documentation")
	proto.RegisterType((*PkgInfo)(nil), "p4.config.PkgInfo")
	proto.RegisterType((*P4Ids)(nil), "p4.config.P4Ids")
	proto.RegisterType((*Preamble)(nil), "p4.config.Preamble")
	proto.RegisterType((*Extern)(nil), "p4.config.Extern")
	proto.RegisterType((*ExternInstance)(nil), "p4.config.ExternInstance")
	proto.RegisterType((*MatchField)(nil), "p4.config.MatchField")
	proto.RegisterType((*Table)(nil), "p4.config.Table")
	proto.RegisterType((*ActionRef)(nil), "p4.config.ActionRef")
	proto.RegisterType((*Action)(nil), "p4.config.Action")
	proto.RegisterType((*Action_Param)(nil), "p4.config.Action.Param")
	proto.RegisterType((*ActionProfile)(nil), "p4.config.ActionProfile")
	proto.RegisterType((*CounterSpec)(nil), "p4.config.CounterSpec")
	proto.RegisterType((*Counter)(nil), "p4.config.Counter")
	proto.RegisterType((*DirectCounter)(nil), "p4.config.DirectCounter")
	proto.RegisterType((*MeterSpec)(nil), "p4.config.MeterSpec")
	proto.RegisterType((*Meter)(nil), "p4.config.Meter")
	proto.RegisterType((*DirectMeter)(nil), "p4.config.DirectMeter")
	proto.RegisterType((*ControllerPacketMetadata)(nil), "p4.config.ControllerPacketMetadata")
	proto.RegisterType((*ControllerPacketMetadata_Metadata)(nil), "p4.config.ControllerPacketMetadata.Metadata")
	proto.RegisterType((*ValueSet)(nil), "p4.config.ValueSet")
	proto.RegisterType((*Register)(nil), "p4.config.Register")
	proto.RegisterType((*Digest)(nil), "p4.config.Digest")
	proto.RegisterEnum("p4.config.P4Ids_Prefix", P4Ids_Prefix_name, P4Ids_Prefix_value)
	proto.RegisterEnum("p4.config.MatchField_MatchType", MatchField_MatchType_name, MatchField_MatchType_value)
	proto.RegisterEnum("p4.config.CounterSpec_Unit", CounterSpec_Unit_name, CounterSpec_Unit_value)
	proto.RegisterEnum("p4.config.MeterSpec_Unit", MeterSpec_Unit_name, MeterSpec_Unit_value)
	proto.RegisterEnum("p4.config.MeterSpec_Type", MeterSpec_Type_name, MeterSpec_Type_value)
}

func init() { proto.RegisterFile("p4/config/p4info.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5f, 0x6f, 0xe3, 0x4a,
	0x15, 0xbf, 0x76, 0xfe, 0xd9, 0x27, 0x7f, 0xae, 0x3b, 0xed, 0x76, 0xbd, 0xbd, 0x0f, 0x54, 0xbe,
	0x08, 0xaa, 0xbd, 0xf7, 0x26, 0xa2, 0x14, 0xc1, 0x0a, 0x81, 0xe4, 0x4d, 0xbc, 0x6d, 0x44, 0x9a,
	0x44, 0x13, 0x77, 0xd9, 0x7d, 0xb2, 0x5c, 0x7b, 0x92, 0x5a, 0x4d, 0x6c, 0xcb, 0x76, 0xba, 0xdb,
	0x7d, 0x42, 0xf0, 0xc0, 0x2b, 0x20, 0xe0, 0x6b, 0xf0, 0x2d, 0x78, 0xe5, 0x73, 0xf0, 0x15, 0x90,
	0x10, 0x68, 0x66, 0x6c, 0xd7, 0xa9, 0xbb, 0xab, 0x06, 0x69, 0x79, 0x9b, 0x39, 0xe7, 0x77, 0xce,
	0x9c, 0x99, 0xdf, 0x99, 0x73, 0x66, 0x60, 0x3f, 0x3c, 0xe9, 0x39, 0x81, 0x3f, 0xf7, 0x16, 0xbd,
	0xf0, 0xc4, 0xf3, 0xe7, 0x41, 0x37, 0x8c, 0x82, 0x24, 0x40, 0x72, 0x78, 0xd2, 0xe5, 0xf2, 0x83,
	0x67, 0x8b, 0x20, 0x58, 0x2c, 0x49, 0x8f, 0x29, 0x2e, 0xd7, 0xf3, 0x9e, 0xed, 0xdf, 0x72, 0x94,
	0xf6, 0x8f, 0x1a, 0xd4, 0xa7, 0x27, 0x43, 0x7f, 0x1e, 0xa0, 0xef, 0x40, 0x0a, 0xaf, 0x17, 0x16,
	0x75, 0xa1, 0x0a, 0x87, 0xc2, 0x51, 0xf3, 0x18, 0x75, 0x73, 0x1f, 0xdd, 0xe9, 0xf5, 0x82, 0xa2,
	0x70, 0x23, 0xe4, 0x03, 0x74, 0x04, 0xf5, 0xc4, 0xbe, 0x5c, 0x92, 0x58, 0x15, 0x0f, 0x2b, 0x47,
	0xcd, 0x63, 0xa5, 0x00, 0x36, 0xa9, 0x02, 0xa7, 0x7a, 0xf4, 0x0d, 0x34, 0x6c, 0x27, 0xf1, 0x02,
	0x3f, 0x56, 0x2b, 0x0c, 0xba, 0x53, 0x80, 0xea, 0x4c, 0x83, 0x33, 0x04, 0xd2, 0xe1, 0x4b, 0x3e,
	0xb4, 0xc2, 0x28, 0x98, 0x7b, 0xd4, 0x7f, 0x95, 0x19, 0xa9, 0x25, 0xa3, 0x29, 0x07, 0xe0, 0x8e,
	0x5d, 0x9c, 0xc6, 0xa8, 0x0b, 0x92, 0x13, 0xac, 0xfd, 0x84, 0x44, 0xb1, 0x5a, 0x63, 0xb6, 0xc5,
	0x8d, 0xf4, 0xb9, 0x0a, 0xe7, 0x18, 0xba, 0xa4, 0xeb, 0x45, 0xc4, 0x49, 0xac, 0xdc, 0xac, 0x5e,
	0x5a, 0x72, 0xc0, 0x10, 0x99, 0x71, 0xc7, 0x2d, 0x4e, 0x63, 0x7a, 0x18, 0x2b, 0xc2, 0x2c, 0x1b,
	0xa5, 0xc3, 0x38, 0xa7, 0x0a, 0x9c, 0xea, 0xd1, 0xcf, 0xa1, 0x9d, 0x2e, 0x96, 0x1a, 0x48, 0xcc,
	0x60, 0xbf, 0xb4, 0x14, 0x37, 0x6b, 0xb9, 0x77, 0x93, 0x18, 0xd9, 0x70, 0xe0, 0x04, 0x7e, 0x12,
	0x05, 0xcb, 0x25, 0x89, 0xac, 0xd0, 0x76, 0xae, 0x09, 0xf3, 0x63, 0xbb, 0x76, 0x62, 0xab, 0x32,
	0xf3, 0xf4, 0xf5, 0xc6, 0x5e, 0x33, 0xf0, 0x94, 0x61, 0xcf, 0x53, 0x28, 0x56, 0x9d, 0x8f, 0x68,
	0xd0, 0x31, 0xc0, 0x8d, 0xbd, 0x5c, 0x13, 0x2b, 0x26, 0x49, 0xac, 0x02, 0x73, 0xb9, 0x5b, 0x70,
	0xf9, 0x9a, 0x2a, 0x67, 0x24, 0xc1, 0xf2, 0x4d, 0x3a, 0x8a, 0xd1, 0x8f, 0x40, 0x8e, 0xc8, 0xc2,
	0x8b, 0xd9, 0x7e, 0x9a, 0x25, 0x13, 0x9c, 0xea, 0xf0, 0x1d, 0x8a, 0xe6, 0x84, 0xeb, 0x2d, 0x48,
	0x9c, 0xc4, 0x6a, 0xab, 0x94, 0x13, 0x03, 0xa6, 0xc1, 0x19, 0x82, 0x82, 0xc9, 0xfb, 0x84, 0x44,
	0x7e, 0xac, 0xba, 0x25, 0xb0, 0xc1, 0x34, 0x38, 0x43, 0x68, 0xa7, 0xd0, 0x1e, 0x04, 0xce, 0x7a,
	0x45, 0xfc, 0xc4, 0xa6, 0x69, 0x81, 0xf6, 0xa0, 0x76, 0x19, 0x79, 0x64, 0xce, 0x92, 0x5a, 0xc6,
	0x7c, 0x82, 0x0e, 0xa1, 0xe9, 0x92, 0xd8, 0x89, 0xbc, 0x90, 0x82, 0x54, 0x91, 0xe9, 0x8a, 0x22,
	0xed, 0x9f, 0x02, 0x34, 0xd2, 0xac, 0x47, 0x08, 0xaa, 0xbe, 0xbd, 0x22, 0xa9, 0x0b, 0x36, 0x46,
	0x2a, 0x34, 0x6e, 0x48, 0x14, 0xdf, 0x59, 0x67, 0x53, 0xf4, 0x1c, 0x2a, 0x6e, 0xe0, 0xa8, 0x15,
	0x76, 0x89, 0x36, 0x92, 0xa8, 0x18, 0x18, 0xa6, 0x20, 0x1a, 0x87, 0xed, 0xfb, 0x01, 0x17, 0xf1,
	0x5c, 0x97, 0x71, 0x51, 0x44, 0xd7, 0xb6, 0x23, 0xe7, 0x4a, 0xad, 0xf1, 0xb5, 0xe9, 0x18, 0x69,
	0xd0, 0x0a, 0xa2, 0x85, 0xed, 0x7b, 0x1f, 0x18, 0x48, 0xad, 0x33, 0xdd, 0x86, 0x8c, 0xc6, 0x47,
	0x59, 0xb6, 0x9d, 0x44, 0x6d, 0xf0, 0xf8, 0xd2, 0x29, 0x52, 0xa0, 0xb2, 0x8e, 0x96, 0xaa, 0xc4,
	0xa4, 0x74, 0xa8, 0xfd, 0x5e, 0x84, 0xda, 0xf4, 0x64, 0xe8, 0xc6, 0xda, 0xbf, 0x05, 0xa8, 0x4f,
	0x23, 0x32, 0xf7, 0xde, 0xa3, 0x2f, 0xa1, 0x79, 0x31, 0x9e, 0x4d, 0x8d, 0xfe, 0xf0, 0xd5, 0xd0,
	0x18, 0x28, 0x5f, 0x20, 0x80, 0xba, 0xde, 0x37, 0x87, 0x93, 0xb1, 0x22, 0x20, 0x19, 0x6a, 0xa6,
	0xfe, 0x72, 0x64, 0x28, 0x22, 0x6a, 0x83, 0xfc, 0x5a, 0x1f, 0x5d, 0x18, 0xd6, 0xcc, 0x30, 0x95,
	0x0a, 0x7a, 0x02, 0x3b, 0xfd, 0xc9, 0xd8, 0xc4, 0x93, 0xd1, 0xc8, 0xc0, 0xd6, 0x99, 0xa1, 0x0f,
	0x0c, 0xac, 0x54, 0xa9, 0x78, 0x3a, 0xd3, 0x2d, 0xe3, 0x8d, 0x69, 0xe0, 0xf1, 0xcc, 0x9a, 0x99,
	0x3a, 0x36, 0x15, 0x05, 0x21, 0xe8, 0x70, 0x9f, 0xd6, 0x14, 0x4f, 0x5e, 0x0d, 0x47, 0x86, 0xb2,
	0x83, 0x9a, 0xd0, 0xe8, 0x4f, 0x2e, 0xc6, 0xa6, 0x81, 0x15, 0x44, 0x01, 0x83, 0x21, 0x36, 0xfa,
	0xa6, 0x95, 0xc9, 0x76, 0xe9, 0xe2, 0xe7, 0x06, 0x1d, 0xee, 0x21, 0x05, 0x5a, 0xa9, 0x9a, 0x4b,
	0x9e, 0xa0, 0x16, 0x48, 0xd8, 0x38, 0x1d, 0xce, 0xe8, 0x6c, 0x9f, 0xc6, 0x3c, 0x18, 0x9e, 0x1a,
	0x33, 0x53, 0x79, 0x8a, 0x54, 0xd8, 0x9d, 0x98, 0x67, 0x06, 0xbe, 0x17, 0xc4, 0x6f, 0x04, 0x24,
	0x41, 0xe5, 0x5c, 0x7f, 0xa3, 0xfc, 0x47, 0xd0, 0xfe, 0x24, 0x80, 0x34, 0x8d, 0x88, 0xbd, 0xba,
	0x5c, 0x12, 0xd4, 0x01, 0xd1, 0x73, 0x19, 0xe9, 0x6d, 0x2c, 0x7a, 0x6e, 0x9e, 0x06, 0x62, 0x21,
	0x0d, 0xf6, 0xa0, 0x66, 0x2f, 0x3d, 0x3b, 0x66, 0x74, 0xcb, 0x98, 0x4f, 0x1e, 0x41, 0x6b, 0x9a,
	0x24, 0xb5, 0x47, 0x24, 0x89, 0xf6, 0x47, 0x01, 0xea, 0x3c, 0xcf, 0xd1, 0xf7, 0xa1, 0xc3, 0x33,
	0xdd, 0x4a, 0x6e, 0x43, 0x62, 0xe5, 0xe1, 0xb5, 0xb8, 0xd4, 0xbc, 0x0d, 0xc9, 0xd0, 0x45, 0x47,
	0xa0, 0x14, 0x51, 0x85, 0xa0, 0x3b, 0x77, 0xb8, 0x31, 0x0d, 0xff, 0xa7, 0x20, 0x7b, 0x7e, 0x9c,
	0xd8, 0xbe, 0x43, 0xb2, 0xf2, 0xfc, 0xac, 0x74, 0xbb, 0x86, 0x29, 0x02, 0xdf, 0x61, 0xb5, 0x6b,
	0xe8, 0x6c, 0x2a, 0x51, 0x0f, 0xa4, 0x30, 0x3d, 0xb9, 0xb4, 0x81, 0x14, 0xab, 0x40, 0x76, 0xa8,
	0x38, 0x07, 0xa1, 0x23, 0xa8, 0xb2, 0x6e, 0x23, 0x32, 0xf0, 0x5e, 0x97, 0xb7, 0xa9, 0x6e, 0xd6,
	0xa6, 0xba, 0xba, 0x7f, 0x8b, 0x19, 0x42, 0xfb, 0x9b, 0x08, 0x70, 0x6e, 0x27, 0xce, 0xd5, 0x2b,
	0x8f, 0x2c, 0xdd, 0x47, 0xf1, 0x72, 0x8f, 0x81, 0x4a, 0x99, 0x81, 0x03, 0x90, 0x2e, 0xbd, 0xe4,
	0x9d, 0xe7, 0x26, 0x57, 0x6a, 0xf5, 0x50, 0x38, 0xaa, 0xe1, 0x7c, 0x8e, 0x7e, 0x09, 0xb0, 0xa2,
	0xeb, 0xb1, 0xf3, 0x63, 0x24, 0x75, 0x8e, 0xbf, 0x57, 0x2c, 0xea, 0x79, 0x30, 0x7c, 0x48, 0xcf,
	0x13, 0xcb, 0xab, 0x6c, 0x98, 0xb1, 0x5b, 0x7f, 0x0c, 0xbb, 0x33, 0x90, 0x73, 0x1f, 0xe5, 0x4b,
	0x27, 0x43, 0xed, 0xb5, 0x3e, 0x1a, 0x0e, 0xf8, 0x9d, 0x33, 0xde, 0xe8, 0x7d, 0x53, 0x11, 0x51,
	0x03, 0x2a, 0xa3, 0xe9, 0xb9, 0x52, 0xa1, 0x77, 0x85, 0xe6, 0xb2, 0x8e, 0xdf, 0x2a, 0x55, 0x0a,
	0xc0, 0xfa, 0xf8, 0xd4, 0x50, 0x6a, 0xda, 0xbf, 0x2a, 0x50, 0x63, 0x6d, 0x78, 0x7b, 0x5a, 0x7e,
	0x06, 0x2d, 0xbe, 0xf7, 0x39, 0xdd, 0x5f, 0xd6, 0xdf, 0x9f, 0x3c, 0xb8, 0x7b, 0xdc, 0x5c, 0xe5,
	0xe3, 0x18, 0xfd, 0x04, 0x9a, 0x69, 0xf3, 0x8e, 0xc8, 0x3c, 0x4b, 0xa7, 0xbd, 0x72, 0xb7, 0x27,
	0x73, 0x0c, 0x76, 0x36, 0xa4, 0x66, 0x4f, 0x9d, 0xc0, 0x8f, 0x13, 0xcb, 0x25, 0x73, 0x7b, 0xbd,
	0x4c, 0xac, 0xd4, 0x89, 0xe7, 0x32, 0x5e, 0xda, 0x78, 0x8f, 0xa9, 0x07, 0x5c, 0xcb, 0x7d, 0x0c,
	0x5d, 0x34, 0x83, 0x1f, 0x3e, 0x68, 0x76, 0x65, 0xc7, 0xd6, 0x6a, 0xcd, 0x1e, 0x1f, 0x56, 0x68,
	0x47, 0xf6, 0x2a, 0x66, 0x04, 0x4a, 0x58, 0x2b, 0xbb, 0x39, 0xb3, 0xe3, 0x73, 0x0e, 0x9d, 0x32,
	0x24, 0xfa, 0x06, 0x76, 0xbc, 0x55, 0xb8, 0x24, 0x39, 0x47, 0x34, 0x8a, 0x3a, 0x8b, 0x42, 0xd9,
	0x54, 0x0c, 0x5d, 0xd4, 0x85, 0xdd, 0xb4, 0x99, 0x47, 0x24, 0x0e, 0xd6, 0x91, 0x43, 0x2f, 0x24,
	0x7f, 0x03, 0xb4, 0xf1, 0x0e, 0x57, 0xe1, 0x54, 0x33, 0x74, 0x59, 0x29, 0x8f, 0xbd, 0x0f, 0x84,
	0x55, 0xde, 0x0a, 0x66, 0x63, 0xf4, 0x2d, 0xa0, 0x77, 0x5e, 0x72, 0x65, 0x11, 0x3f, 0x89, 0x6e,
	0xad, 0xc4, 0x5b, 0x91, 0x60, 0x9d, 0xa8, 0x32, 0x0b, 0x58, 0xa1, 0x1a, 0x83, 0x2a, 0x4c, 0x2e,
	0xa7, 0xd7, 0xdf, 0x8b, 0x2d, 0xbe, 0x6d, 0x16, 0xb6, 0x0a, 0x0c, 0xd9, 0xf2, 0xe2, 0x3e, 0x15,
	0x32, 0xca, 0xb5, 0x5f, 0x80, 0x9c, 0x9f, 0x74, 0xe9, 0xb2, 0xdc, 0xbb, 0x18, 0x62, 0xe9, 0x62,
	0x68, 0xbf, 0x15, 0xa1, 0xce, 0xed, 0xb7, 0x4f, 0x9e, 0x1e, 0xd4, 0xd3, 0x33, 0xe7, 0x69, 0xf3,
	0xb4, 0xc4, 0x7e, 0x97, 0x9d, 0x34, 0x4e, 0x61, 0x07, 0x7f, 0x11, 0xa0, 0xc6, 0x24, 0xff, 0x87,
	0x5b, 0xbd, 0x4d, 0xcd, 0xfd, 0xab, 0x00, 0xed, 0x8d, 0x77, 0xe6, 0xf6, 0x67, 0xf1, 0x15, 0xc8,
	0x3c, 0x0b, 0xbd, 0xf4, 0x16, 0xb5, 0xb1, 0xc4, 0x04, 0x34, 0x17, 0xbe, 0x86, 0x36, 0xe3, 0x3d,
	0x26, 0x4b, 0xe2, 0x24, 0x41, 0xc4, 0xfa, 0x87, 0x84, 0x5b, 0x54, 0x38, 0x4b, 0x65, 0x79, 0xc2,
	0x54, 0xef, 0x12, 0x46, 0xbb, 0x85, 0x66, 0xfa, 0xee, 0x9c, 0x85, 0xc4, 0x41, 0x3d, 0xa8, 0xae,
	0x7d, 0x2f, 0x61, 0x11, 0x75, 0x8e, 0xbf, 0x2a, 0xbf, 0x74, 0x29, 0xaa, 0x7b, 0xe1, 0x7b, 0x09,
	0x66, 0x40, 0xed, 0x05, 0x54, 0xe9, 0xec, 0xc1, 0x4a, 0xf3, 0xf2, 0xad, 0x69, 0xcc, 0x14, 0x81,
	0x56, 0x95, 0xa9, 0xde, 0xff, 0x95, 0x61, 0xce, 0x14, 0x11, 0x49, 0x50, 0x7d, 0x39, 0x31, 0xcf,
	0x94, 0x8a, 0xf6, 0x01, 0x1a, 0xa9, 0xd3, 0xed, 0x0f, 0xe3, 0x39, 0x54, 0xe3, 0x90, 0x38, 0x69,
	0xb1, 0xdf, 0x7f, 0x38, 0x4e, 0xcc, 0x30, 0xf9, 0xb6, 0x2b, 0x85, 0x6d, 0xff, 0x59, 0x80, 0xf6,
	0xc6, 0x23, 0xfc, 0xf3, 0x86, 0xf0, 0x83, 0xfc, 0x53, 0x90, 0x51, 0xc8, 0xa2, 0x69, 0xe3, 0xf4,
	0xf9, 0x6e, 0x72, 0x1e, 0xb5, 0xbf, 0x0b, 0x20, 0xb3, 0xd7, 0x39, 0x23, 0xe3, 0xbb, 0x0d, 0x32,
	0x9e, 0xdd, 0xff, 0x05, 0xdc, 0xa3, 0x82, 0xc2, 0x59, 0x7f, 0x11, 0x3f, 0x01, 0x67, 0x9d, 0x85,
	0xc1, 0xb4, 0xde, 0x96, 0xcc, 0x69, 0xcf, 0xa1, 0xca, 0x9a, 0xca, 0x0e, 0xb4, 0xfb, 0x93, 0xd1,
	0x04, 0x5b, 0x17, 0x63, 0xfd, 0xd7, 0x3a, 0x36, 0x94, 0x2f, 0xa8, 0x0f, 0x2e, 0xe2, 0x02, 0x41,
	0xbb, 0x81, 0x1a, 0x5b, 0xf4, 0x7f, 0x6a, 0xe3, 0x85, 0x63, 0xdd, 0x7b, 0x68, 0x17, 0x9f, 0xe0,
	0xf5, 0x0f, 0x02, 0x34, 0x0b, 0x3f, 0x9e, 0xcf, 0xb9, 0xfc, 0x63, 0x39, 0xfd, 0x9d, 0x08, 0xea,
	0xc7, 0xbe, 0x4e, 0xdb, 0xc7, 0x77, 0x06, 0x52, 0xfe, 0x45, 0xe3, 0x35, 0xf1, 0xdb, 0x47, 0x7c,
	0xd1, 0xba, 0xf9, 0x5f, 0x2d, 0xb7, 0x3e, 0x58, 0x82, 0x94, 0x87, 0xf1, 0xd9, 0x8b, 0xa5, 0x76,
	0x0d, 0x52, 0xf6, 0xd9, 0xdb, 0x7e, 0xd3, 0x45, 0xc7, 0xe2, 0xbd, 0x2a, 0x5c, 0xcc, 0x82, 0x5a,
	0x9a, 0x05, 0x13, 0x90, 0xb2, 0x6f, 0xe2, 0xf6, 0x8b, 0x3d, 0xe4, 0xf0, 0x05, 0xd4, 0xf9, 0x37,
	0x72, 0x6b, 0x77, 0x97, 0x75, 0xf6, 0x00, 0xfd, 0xf1, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x40,
	0xee, 0xaf, 0x9c, 0x5a, 0x11, 0x00, 0x00,
}
